###############################################################################
# DatadogAgent Custom Resource
###############################################################################

apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  global:
    credentials:
      apiSecret:
        secretName: datadog-keys
        keyName: api-key
      appSecret:
        secretName: datadog-keys
        keyName: app-key

    site: datadoghq.com

    tags:
      - "env:development"
      - "cluster:platform-cluster"
      - "team:devops"
      - "project:cloud-platform-engineering"

  features:
    liveProcessCollection:
      enabled: true

    logCollection:
      enabled: true
      containerCollectAll: true

    apm:
      enabled: true
      hostPortConfig:
        enabled: false

    clusterChecks:
      enabled: true

    orchestratorExplorer:
      enabled: true

  override:
    clusterAgent:
      replicas: 1
      containers:
        cluster-agent:
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi

    nodeAgent:
      containers:
        agent:
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi
